apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-web
  description: An example web of a Backstage application.
  tags:
    - java
    - nomad
    - frontend
spec:
  type: website
  lifecycle: experimental
  owner: frontent
  providesApis: 
    - example-api